dist: focal
# Minimal because we do everything in docker
language: minimal
services:
  - docker
before_install:
  - make build-ci
script:
  - make travis
notifications:
  email:
    on_success: never
