dist: focal
# Select something that is not JS since we are only using docker
language: php
services:
  - docker
before_install:
  - make build-ci
script:
  - make travis
notifications:
  email:
    on_success: never
